<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('country', function (Blueprint $table) {
            $table->id('country_id');
            $table->string('sortname', 3);
            $table->string('name', 150);
            $table->integer('phonecode');
        });

        // Insert default data
        $country = [
            array("country_id"=>"1","sortname"=>"AF","name"=>"Afghanistan","phonecode"=>"93"),
            array("country_id"=>"2","sortname"=>"AL","name"=>"Albania","phonecode"=>"355"),
            array("country_id"=>"3","sortname"=>"DZ","name"=>"Algeria","phonecode"=>"213"),
            array("country_id"=>"4","sortname"=>"AS","name"=>"American Samoa","phonecode"=>"1684"),
            array("country_id"=>"5","sortname"=>"AD","name"=>"Andorra","phonecode"=>"376"),
            array("country_id"=>"6","sortname"=>"AO","name"=>"Angola","phonecode"=>"244"),
            array("country_id"=>"7","sortname"=>"AI","name"=>"Anguilla","phonecode"=>"1264"),
            array("country_id"=>"8","sortname"=>"AQ","name"=>"Antarctica","phonecode"=>"0"),
            array("country_id"=>"9","sortname"=>"AG","name"=>"Antigua And Barbuda","phonecode"=>"1268"),
            array("country_id"=>"10","sortname"=>"AR","name"=>"Argentina","phonecode"=>"54"),
            array("country_id"=>"11","sortname"=>"AM","name"=>"Armenia","phonecode"=>"374"),
            array("country_id"=>"12","sortname"=>"AW","name"=>"Aruba","phonecode"=>"297"),
            array("country_id"=>"13","sortname"=>"AU","name"=>"Australia","phonecode"=>"61"),
            array("country_id"=>"14","sortname"=>"AT","name"=>"Austria","phonecode"=>"43"),
            array("country_id"=>"15","sortname"=>"AZ","name"=>"Azerbaijan","phonecode"=>"994"),
            array("country_id"=>"16","sortname"=>"BS","name"=>"Bahamas The","phonecode"=>"1242"),
            array("country_id"=>"17","sortname"=>"BH","name"=>"Bahrain","phonecode"=>"973"),
            array("country_id"=>"18","sortname"=>"BD","name"=>"Bangladesh","phonecode"=>"880"),
            array("country_id"=>"19","sortname"=>"BB","name"=>"Barbados","phonecode"=>"1246"),
            array("country_id"=>"20","sortname"=>"BY","name"=>"Belarus","phonecode"=>"375"),
            array("country_id"=>"21","sortname"=>"BE","name"=>"Belgium","phonecode"=>"32"),
            array("country_id"=>"22","sortname"=>"BZ","name"=>"Belize","phonecode"=>"501"),
            array("country_id"=>"23","sortname"=>"BJ","name"=>"Benin","phonecode"=>"229"),
            array("country_id"=>"24","sortname"=>"BM","name"=>"Bermuda","phonecode"=>"1441"),
            array("country_id"=>"25","sortname"=>"BT","name"=>"Bhutan","phonecode"=>"975"),
            array("country_id"=>"26","sortname"=>"BO","name"=>"Bolivia","phonecode"=>"591"),
            array("country_id"=>"27","sortname"=>"BA","name"=>"Bosnia and Herzegovina","phonecode"=>"387"),
            array("country_id"=>"28","sortname"=>"BW","name"=>"Botswana","phonecode"=>"267"),
            array("country_id"=>"29","sortname"=>"BV","name"=>"Bouvet Island","phonecode"=>"0"),
            array("country_id"=>"30","sortname"=>"BR","name"=>"Brazil","phonecode"=>"55"),
            array("country_id"=>"31","sortname"=>"IO","name"=>"British Indian Ocean Territory","phonecode"=>"246"),
            array("country_id"=>"32","sortname"=>"BN","name"=>"Brunei","phonecode"=>"673"),
            array("country_id"=>"33","sortname"=>"BG","name"=>"Bulgaria","phonecode"=>"359"),
            array("country_id"=>"34","sortname"=>"BF","name"=>"Burkina Faso","phonecode"=>"226"),
            array("country_id"=>"35","sortname"=>"BI","name"=>"Burundi","phonecode"=>"257"),
            array("country_id"=>"36","sortname"=>"KH","name"=>"Cambodia","phonecode"=>"855"),
            array("country_id"=>"37","sortname"=>"CM","name"=>"Cameroon","phonecode"=>"237"),
            array("country_id"=>"38","sortname"=>"CA","name"=>"Canada","phonecode"=>"1"),
            array("country_id"=>"39","sortname"=>"CV","name"=>"Cape Verde","phonecode"=>"238"),
            array("country_id"=>"40","sortname"=>"KY","name"=>"Cayman Islands","phonecode"=>"1345"),
            array("country_id"=>"41","sortname"=>"CF","name"=>"Central African Republic","phonecode"=>"236"),
            array("country_id"=>"42","sortname"=>"TD","name"=>"Chad","phonecode"=>"235"),
            array("country_id"=>"43","sortname"=>"CL","name"=>"Chile","phonecode"=>"56"),
            array("country_id"=>"44","sortname"=>"CN","name"=>"China","phonecode"=>"86"),
            array("country_id"=>"45","sortname"=>"CX","name"=>"Christmas Island","phonecode"=>"61"),
            array("country_id"=>"46","sortname"=>"CC","name"=>"Cocos (Keeling) Islands","phonecode"=>"672"),
            array("country_id"=>"47","sortname"=>"CO","name"=>"Colombia","phonecode"=>"57"),
            array("country_id"=>"48","sortname"=>"KM","name"=>"Comoros","phonecode"=>"269"),
            array("country_id"=>"49","sortname"=>"CG","name"=>"Republic Of The Congo","phonecode"=>"242"),
            array("country_id"=>"50","sortname"=>"CD","name"=>"Democratic Republic Of The Congo","phonecode"=>"242"),
            array("country_id"=>"51","sortname"=>"CK","name"=>"Cook Islands","phonecode"=>"682"),
            array("country_id"=>"52","sortname"=>"CR","name"=>"Costa Rica","phonecode"=>"506"),
            array("country_id"=>"53","sortname"=>"CI","name"=>"Cote D'Ivoire (Ivory Coast)","phonecode"=>"225"),
            array("country_id"=>"54","sortname"=>"HR","name"=>"Croatia (Hrvatska)","phonecode"=>"385"),
            array("country_id"=>"55","sortname"=>"CU","name"=>"Cuba","phonecode"=>"53"),
            array("country_id"=>"56","sortname"=>"CY","name"=>"Cyprus","phonecode"=>"357"),
            array("country_id"=>"57","sortname"=>"CZ","name"=>"Czech Republic","phonecode"=>"420"),
            array("country_id"=>"58","sortname"=>"DK","name"=>"Denmark","phonecode"=>"45"),
            array("country_id"=>"59","sortname"=>"DJ","name"=>"Djibouti","phonecode"=>"253"),
            array("country_id"=>"60","sortname"=>"DM","name"=>"Dominica","phonecode"=>"1767"),
            array("country_id"=>"61","sortname"=>"DO","name"=>"Dominican Republic","phonecode"=>"1809"),
            array("country_id"=>"62","sortname"=>"TP","name"=>"East Timor","phonecode"=>"670"),
            array("country_id"=>"63","sortname"=>"EC","name"=>"Ecuador","phonecode"=>"593"),
            array("country_id"=>"64","sortname"=>"EG","name"=>"Egypt","phonecode"=>"20"),
            array("country_id"=>"65","sortname"=>"SV","name"=>"El Salvador","phonecode"=>"503"),
            array("country_id"=>"66","sortname"=>"GQ","name"=>"Equatorial Guinea","phonecode"=>"240"),
            array("country_id"=>"67","sortname"=>"ER","name"=>"Eritrea","phonecode"=>"291"),
            array("country_id"=>"68","sortname"=>"EE","name"=>"Estonia","phonecode"=>"372"),
            array("country_id"=>"69","sortname"=>"ET","name"=>"Ethiopia","phonecode"=>"251"),
            array("country_id"=>"70","sortname"=>"XA","name"=>"External Territories of Australia","phonecode"=>"61"),
            array("country_id"=>"71","sortname"=>"FK","name"=>"Falkland Islands","phonecode"=>"500"),
            array("country_id"=>"72","sortname"=>"FO","name"=>"Faroe Islands","phonecode"=>"298"),
            array("country_id"=>"73","sortname"=>"FJ","name"=>"Fiji Islands","phonecode"=>"679"),
            array("country_id"=>"74","sortname"=>"FI","name"=>"Finland","phonecode"=>"358"),
            array("country_id"=>"75","sortname"=>"FR","name"=>"France","phonecode"=>"33"),
            array("country_id"=>"76","sortname"=>"GF","name"=>"French Guiana","phonecode"=>"594"),
            array("country_id"=>"77","sortname"=>"PF","name"=>"French Polynesia","phonecode"=>"689"),
            array("country_id"=>"78","sortname"=>"TF","name"=>"French Southern Territories","phonecode"=>"0"),
            array("country_id"=>"79","sortname"=>"GA","name"=>"Gabon","phonecode"=>"241"),
            array("country_id"=>"80","sortname"=>"GM","name"=>"Gambia The","phonecode"=>"220"),
            array("country_id"=>"81","sortname"=>"GE","name"=>"Georgia","phonecode"=>"995"),
            array("country_id"=>"82","sortname"=>"DE","name"=>"Germany","phonecode"=>"49"),
            array("country_id"=>"83","sortname"=>"GH","name"=>"Ghana","phonecode"=>"233"),
            array("country_id"=>"84","sortname"=>"GI","name"=>"Gibraltar","phonecode"=>"350"),
            array("country_id"=>"85","sortname"=>"GR","name"=>"Greece","phonecode"=>"30"),
            array("country_id"=>"86","sortname"=>"GL","name"=>"Greenland","phonecode"=>"299"),
            array("country_id"=>"87","sortname"=>"GD","name"=>"Grenada","phonecode"=>"1473"),
            array("country_id"=>"88","sortname"=>"GP","name"=>"Guadeloupe","phonecode"=>"590"),
            array("country_id"=>"89","sortname"=>"GU","name"=>"Guam","phonecode"=>"1671"),
            array("country_id"=>"90","sortname"=>"GT","name"=>"Guatemala","phonecode"=>"502"),
            array("country_id"=>"91","sortname"=>"XU","name"=>"Guernsey and Alderney","phonecode"=>"44"),
            array("country_id"=>"92","sortname"=>"GN","name"=>"Guinea","phonecode"=>"224"),
            array("country_id"=>"93","sortname"=>"GW","name"=>"Guinea-Bissau","phonecode"=>"245"),
            array("country_id"=>"94","sortname"=>"GY","name"=>"Guyana","phonecode"=>"592"),
            array("country_id"=>"95","sortname"=>"HT","name"=>"Haiti","phonecode"=>"509"),
            array("country_id"=>"96","sortname"=>"HM","name"=>"Heard and McDonald Islands","phonecode"=>"0"),
            array("country_id"=>"97","sortname"=>"HN","name"=>"Honduras","phonecode"=>"504"),
            array("country_id"=>"98","sortname"=>"HK","name"=>"Hong Kong S.A.R.","phonecode"=>"852"),
            array("country_id"=>"99","sortname"=>"HU","name"=>"Hungary","phonecode"=>"36"),
            array("country_id"=>"100","sortname"=>"IS","name"=>"Iceland","phonecode"=>"354"),
            array("country_id"=>"101","sortname"=>"IN","name"=>"India","phonecode"=>"91"),
            array("country_id"=>"102","sortname"=>"ID","name"=>"Indonesia","phonecode"=>"62"),
            array("country_id"=>"103","sortname"=>"IR","name"=>"Iran","phonecode"=>"98"),
            array("country_id"=>"104","sortname"=>"IQ","name"=>"Iraq","phonecode"=>"964"),
            array("country_id"=>"105","sortname"=>"IE","name"=>"Ireland","phonecode"=>"353"),
            array("country_id"=>"106","sortname"=>"IL","name"=>"Israel","phonecode"=>"972"),
            array("country_id"=>"107","sortname"=>"IT","name"=>"Italy","phonecode"=>"39"),
            array("country_id"=>"108","sortname"=>"JM","name"=>"Jamaica","phonecode"=>"1876"),
            array("country_id"=>"109","sortname"=>"JP","name"=>"Japan","phonecode"=>"81"),
            array("country_id"=>"110","sortname"=>"XJ","name"=>"Jersey","phonecode"=>"44"),
            array("country_id"=>"111","sortname"=>"JO","name"=>"Jordan","phonecode"=>"962"),
            array("country_id"=>"112","sortname"=>"KZ","name"=>"Kazakhstan","phonecode"=>"7"),
            array("country_id"=>"113","sortname"=>"KE","name"=>"Kenya","phonecode"=>"254"),
            array("country_id"=>"114","sortname"=>"KI","name"=>"Kiribati","phonecode"=>"686"),
            array("country_id"=>"115","sortname"=>"KP","name"=>"Korea North","phonecode"=>"850"),
            array("country_id"=>"116","sortname"=>"KR","name"=>"Korea South","phonecode"=>"82"),
            array("country_id"=>"117","sortname"=>"KW","name"=>"Kuwait","phonecode"=>"965"),
            array("country_id"=>"118","sortname"=>"KG","name"=>"Kyrgyzstan","phonecode"=>"996"),
            array("country_id"=>"119","sortname"=>"LA","name"=>"Laos","phonecode"=>"856"),
            array("country_id"=>"120","sortname"=>"LV","name"=>"Latvia","phonecode"=>"371"),
            array("country_id"=>"121","sortname"=>"LB","name"=>"Lebanon","phonecode"=>"961"),
            array("country_id"=>"122","sortname"=>"LS","name"=>"Lesotho","phonecode"=>"266"),
            array("country_id"=>"123","sortname"=>"LR","name"=>"Liberia","phonecode"=>"231"),
            array("country_id"=>"124","sortname"=>"LY","name"=>"Libya","phonecode"=>"218"),
            array("country_id"=>"125","sortname"=>"LI","name"=>"Liechtenstein","phonecode"=>"423"),
            array("country_id"=>"126","sortname"=>"LT","name"=>"Lithuania","phonecode"=>"370"),
            array("country_id"=>"127","sortname"=>"LU","name"=>"Luxembourg","phonecode"=>"352"),
            array("country_id"=>"128","sortname"=>"MO","name"=>"Macau S.A.R.","phonecode"=>"853"),
            array("country_id"=>"129","sortname"=>"MK","name"=>"Macedonia","phonecode"=>"389"),
            array("country_id"=>"130","sortname"=>"MG","name"=>"Madagascar","phonecode"=>"261"),
            array("country_id"=>"131","sortname"=>"MW","name"=>"Malawi","phonecode"=>"265"),
            array("country_id"=>"132","sortname"=>"MY","name"=>"Malaysia","phonecode"=>"60"),
            array("country_id"=>"133","sortname"=>"MV","name"=>"Maldives","phonecode"=>"960"),
            array("country_id"=>"134","sortname"=>"ML","name"=>"Mali","phonecode"=>"223"),
            array("country_id"=>"135","sortname"=>"MT","name"=>"Malta","phonecode"=>"356"),
            array("country_id"=>"136","sortname"=>"XM","name"=>"Man (Isle of)","phonecode"=>"44"),
            array("country_id"=>"137","sortname"=>"MH","name"=>"Marshall Islands","phonecode"=>"692"),
            array("country_id"=>"138","sortname"=>"MQ","name"=>"Martinique","phonecode"=>"596"),
            array("country_id"=>"139","sortname"=>"MR","name"=>"Mauritania","phonecode"=>"222"),
            array("country_id"=>"140","sortname"=>"MU","name"=>"Mauritius","phonecode"=>"230"),
            array("country_id"=>"141","sortname"=>"YT","name"=>"Mayotte","phonecode"=>"269"),
            array("country_id"=>"142","sortname"=>"MX","name"=>"Mexico","phonecode"=>"52"),
            array("country_id"=>"143","sortname"=>"FM","name"=>"Micronesia","phonecode"=>"691"),
            array("country_id"=>"144","sortname"=>"MD","name"=>"Moldova","phonecode"=>"373"),
            array("country_id"=>"145","sortname"=>"MC","name"=>"Monaco","phonecode"=>"377"),
            array("country_id"=>"146","sortname"=>"MN","name"=>"Mongolia","phonecode"=>"976"),
            array("country_id"=>"147","sortname"=>"MS","name"=>"Montserrat","phonecode"=>"1664"),
            array("country_id"=>"148","sortname"=>"MA","name"=>"Morocco","phonecode"=>"212"),
            array("country_id"=>"149","sortname"=>"MZ","name"=>"Mozambique","phonecode"=>"258"),
            array("country_id"=>"150","sortname"=>"MM","name"=>"Myanmar","phonecode"=>"95"),
            array("country_id"=>"151","sortname"=>"NA","name"=>"Namibia","phonecode"=>"264"),
            array("country_id"=>"152","sortname"=>"NR","name"=>"Nauru","phonecode"=>"674"),
            array("country_id"=>"153","sortname"=>"NP","name"=>"Nepal","phonecode"=>"977"),
            array("country_id"=>"154","sortname"=>"AN","name"=>"Netherlands Antilles","phonecode"=>"599"),
            array("country_id"=>"155","sortname"=>"NL","name"=>"Netherlands The","phonecode"=>"31"),
            array("country_id"=>"156","sortname"=>"NC","name"=>"New Caledonia","phonecode"=>"687"),
            array("country_id"=>"157","sortname"=>"NZ","name"=>"New Zealand","phonecode"=>"64"),
            array("country_id"=>"158","sortname"=>"NI","name"=>"Nicaragua","phonecode"=>"505"),
            array("country_id"=>"159","sortname"=>"NE","name"=>"Niger","phonecode"=>"227"),
            array("country_id"=>"160","sortname"=>"NG","name"=>"Nigeria","phonecode"=>"234"),
            array("country_id"=>"161","sortname"=>"NU","name"=>"Niue","phonecode"=>"683"),
            array("country_id"=>"162","sortname"=>"NF","name"=>"Norfolk Island","phonecode"=>"672"),
            array("country_id"=>"163","sortname"=>"MP","name"=>"Northern Mariana Islands","phonecode"=>"1670"),
            array("country_id"=>"164","sortname"=>"NO","name"=>"Norway","phonecode"=>"47"),
            array("country_id"=>"165","sortname"=>"OM","name"=>"Oman","phonecode"=>"968"),
            array("country_id"=>"166","sortname"=>"PK","name"=>"Pakistan","phonecode"=>"92"),
            array("country_id"=>"167","sortname"=>"PW","name"=>"Palau","phonecode"=>"680"),
            array("country_id"=>"168","sortname"=>"PS","name"=>"Palestinian Territory Occupied","phonecode"=>"970"),
            array("country_id"=>"169","sortname"=>"PA","name"=>"Panama","phonecode"=>"507"),
            array("country_id"=>"170","sortname"=>"PG","name"=>"Papua new Guinea","phonecode"=>"675"),
            array("country_id"=>"171","sortname"=>"PY","name"=>"Paraguay","phonecode"=>"595"),
            array("country_id"=>"172","sortname"=>"PE","name"=>"Peru","phonecode"=>"51"),
            array("country_id"=>"173","sortname"=>"PH","name"=>"Philippines","phonecode"=>"63"),
            array("country_id"=>"174","sortname"=>"PN","name"=>"Pitcairn Island","phonecode"=>"0"),
            array("country_id"=>"175","sortname"=>"PL","name"=>"Poland","phonecode"=>"48"),
            array("country_id"=>"176","sortname"=>"PT","name"=>"Portugal","phonecode"=>"351"),
            array("country_id"=>"177","sortname"=>"PR","name"=>"Puerto Rico","phonecode"=>"1787"),
            array("country_id"=>"178","sortname"=>"QA","name"=>"Qatar","phonecode"=>"974"),
            array("country_id"=>"179","sortname"=>"RE","name"=>"Reunion","phonecode"=>"262"),
            array("country_id"=>"180","sortname"=>"RO","name"=>"Romania","phonecode"=>"40"),
            array("country_id"=>"181","sortname"=>"RU","name"=>"Russia","phonecode"=>"70"),
            array("country_id"=>"182","sortname"=>"RW","name"=>"Rwanda","phonecode"=>"250"),
            array("country_id"=>"183","sortname"=>"SH","name"=>"Saint Helena","phonecode"=>"290"),
            array("country_id"=>"184","sortname"=>"KN","name"=>"Saint Kitts And Nevis","phonecode"=>"1869"),
            array("country_id"=>"185","sortname"=>"LC","name"=>"Saint Lucia","phonecode"=>"1758"),
            array("country_id"=>"186","sortname"=>"PM","name"=>"Saint Pierre and Miquelon","phonecode"=>"508"),
            array("country_id"=>"187","sortname"=>"VC","name"=>"Saint Vincent And The Grenadines","phonecode"=>"1784"),
            array("country_id"=>"188","sortname"=>"WS","name"=>"Samoa","phonecode"=>"684"),
            array("country_id"=>"189","sortname"=>"SM","name"=>"San Marino","phonecode"=>"378"),
            array("country_id"=>"190","sortname"=>"ST","name"=>"Sao Tome and Principe","phonecode"=>"239"),
            array("country_id"=>"191","sortname"=>"SA","name"=>"Saudi Arabia","phonecode"=>"966"),
            array("country_id"=>"192","sortname"=>"SN","name"=>"Senegal","phonecode"=>"221"),
            array("country_id"=>"193","sortname"=>"RS","name"=>"Serbia","phonecode"=>"381"),
            array("country_id"=>"194","sortname"=>"SC","name"=>"Seychelles","phonecode"=>"248"),
            array("country_id"=>"195","sortname"=>"SL","name"=>"Sierra Leone","phonecode"=>"232"),
            array("country_id"=>"196","sortname"=>"SG","name"=>"Singapore","phonecode"=>"65"),
            array("country_id"=>"197","sortname"=>"SK","name"=>"Slovakia","phonecode"=>"421"),
            array("country_id"=>"198","sortname"=>"SI","name"=>"Slovenia","phonecode"=>"386"),
            array("country_id"=>"199","sortname"=>"XG","name"=>"Smaller Territories of the UK","phonecode"=>"44"),
            array("country_id"=>"200","sortname"=>"SB","name"=>"Solomon Islands","phonecode"=>"677"),
            array("country_id"=>"201","sortname"=>"SO","name"=>"Somalia","phonecode"=>"252"),
            array("country_id"=>"202","sortname"=>"ZA","name"=>"South Africa","phonecode"=>"27"),
            array("country_id"=>"203","sortname"=>"GS","name"=>"South Georgia","phonecode"=>"0"),
            array("country_id"=>"204","sortname"=>"SS","name"=>"South Sudan","phonecode"=>"211"),
            array("country_id"=>"205","sortname"=>"ES","name"=>"Spain","phonecode"=>"34"),
            array("country_id"=>"206","sortname"=>"LK","name"=>"Sri Lanka","phonecode"=>"94"),
            array("country_id"=>"207","sortname"=>"SD","name"=>"Sudan","phonecode"=>"249"),
            array("country_id"=>"208","sortname"=>"SR","name"=>"Suriname","phonecode"=>"597"),
            array("country_id"=>"209","sortname"=>"SJ","name"=>"Svalbard And Jan Mayen Islands","phonecode"=>"47"),
            array("country_id"=>"210","sortname"=>"SZ","name"=>"Swaziland","phonecode"=>"268"),
            array("country_id"=>"211","sortname"=>"SE","name"=>"Sweden","phonecode"=>"46"),
            array("country_id"=>"212","sortname"=>"CH","name"=>"Switzerland","phonecode"=>"41"),
            array("country_id"=>"213","sortname"=>"SY","name"=>"Syria","phonecode"=>"963"),
            array("country_id"=>"214","sortname"=>"TW","name"=>"Taiwan","phonecode"=>"886"),
            array("country_id"=>"215","sortname"=>"TJ","name"=>"Tajikistan","phonecode"=>"992"),
            array("country_id"=>"216","sortname"=>"TZ","name"=>"Tanzania","phonecode"=>"255"),
            array("country_id"=>"217","sortname"=>"TH","name"=>"Thailand","phonecode"=>"66"),
            array("country_id"=>"218","sortname"=>"TG","name"=>"Togo","phonecode"=>"228"),
            array("country_id"=>"219","sortname"=>"TK","name"=>"Tokelau","phonecode"=>"690"),
            array("country_id"=>"220","sortname"=>"TO","name"=>"Tonga","phonecode"=>"676"),
            array("country_id"=>"221","sortname"=>"TT","name"=>"Trinidad And Tobago","phonecode"=>"1868"),
            array("country_id"=>"222","sortname"=>"TN","name"=>"Tunisia","phonecode"=>"216"),
            array("country_id"=>"223","sortname"=>"TR","name"=>"Turkey","phonecode"=>"90"),
            array("country_id"=>"224","sortname"=>"TM","name"=>"Turkmenistan","phonecode"=>"7370"),
            array("country_id"=>"225","sortname"=>"TC","name"=>"Turks And Caicos Islands","phonecode"=>"1649"),
            array("country_id"=>"226","sortname"=>"TV","name"=>"Tuvalu","phonecode"=>"688"),
            array("country_id"=>"227","sortname"=>"UG","name"=>"Uganda","phonecode"=>"256"),
            array("country_id"=>"228","sortname"=>"UA","name"=>"Ukraine","phonecode"=>"380"),
            array("country_id"=>"229","sortname"=>"AE","name"=>"United Arab Emirates","phonecode"=>"971"),
            array("country_id"=>"230","sortname"=>"GB","name"=>"United Kingdom","phonecode"=>"44"),
            array("country_id"=>"231","sortname"=>"US","name"=>"United States","phonecode"=>"1"),
            array("country_id"=>"232","sortname"=>"UM","name"=>"United States Minor Outlying Islands","phonecode"=>"1"),
            array("country_id"=>"233","sortname"=>"UY","name"=>"Uruguay","phonecode"=>"598"),
            array("country_id"=>"234","sortname"=>"UZ","name"=>"Uzbekistan","phonecode"=>"998"),
            array("country_id"=>"235","sortname"=>"VU","name"=>"Vanuatu","phonecode"=>"678"),
            array("country_id"=>"236","sortname"=>"VA","name"=>"Vatican City State (Holy See)","phonecode"=>"39"),
            array("country_id"=>"237","sortname"=>"VE","name"=>"Venezuela","phonecode"=>"58"),
            array("country_id"=>"238","sortname"=>"VN","name"=>"Vietnam","phonecode"=>"84"),
            array("country_id"=>"239","sortname"=>"VG","name"=>"Virgin Islands (British)","phonecode"=>"1284"),
            array("country_id"=>"240","sortname"=>"VI","name"=>"Virgin Islands (US)","phonecode"=>"1340"),
            array("country_id"=>"241","sortname"=>"WF","name"=>"Wallis And Futuna Islands","phonecode"=>"681"),
            array("country_id"=>"242","sortname"=>"EH","name"=>"Western Sahara","phonecode"=>"212"),
            array("country_id"=>"243","sortname"=>"YE","name"=>"Yemen","phonecode"=>"967"),
            array("country_id"=>"244","sortname"=>"YU","name"=>"Yugoslavia","phonecode"=>"38"),
            array("country_id"=>"245","sortname"=>"ZM","name"=>"Zambia","phonecode"=>"260"),
            array("country_id"=>"246","sortname"=>"ZW","name"=>"Zimbabwe","phonecode"=>"263"),
            array("country_id"=>"247","sortname"=>"AF","name"=>"Afghanistan","phonecode"=>"93"),
            array("country_id"=>"248","sortname"=>"AL","name"=>"Albania","phonecode"=>"355"),
            array("country_id"=>"249","sortname"=>"DZ","name"=>"Algeria","phonecode"=>"213"),
            array("country_id"=>"250","sortname"=>"AS","name"=>"American Samoa","phonecode"=>"1684"),
            array("country_id"=>"251","sortname"=>"AD","name"=>"Andorra","phonecode"=>"376"),
            array("country_id"=>"252","sortname"=>"AO","name"=>"Angola","phonecode"=>"244"),
            array("country_id"=>"253","sortname"=>"AI","name"=>"Anguilla","phonecode"=>"1264"),
            array("country_id"=>"254","sortname"=>"AQ","name"=>"Antarctica","phonecode"=>"0"),
            array("country_id"=>"255","sortname"=>"AG","name"=>"Antigua And Barbuda","phonecode"=>"1268"),
            array("country_id"=>"256","sortname"=>"AR","name"=>"Argentina","phonecode"=>"54"),
            array("country_id"=>"257","sortname"=>"AM","name"=>"Armenia","phonecode"=>"374"),
            array("country_id"=>"258","sortname"=>"AW","name"=>"Aruba","phonecode"=>"297"),
            array("country_id"=>"259","sortname"=>"AU","name"=>"Australia","phonecode"=>"61"),
            array("country_id"=>"260","sortname"=>"AT","name"=>"Austria","phonecode"=>"43"),
            array("country_id"=>"261","sortname"=>"AZ","name"=>"Azerbaijan","phonecode"=>"994"),
            array("country_id"=>"262","sortname"=>"BS","name"=>"Bahamas The","phonecode"=>"1242"),
            array("country_id"=>"263","sortname"=>"BH","name"=>"Bahrain","phonecode"=>"973"),
            array("country_id"=>"264","sortname"=>"BD","name"=>"Bangladesh","phonecode"=>"880"),
            array("country_id"=>"265","sortname"=>"BB","name"=>"Barbados","phonecode"=>"1246"),
            array("country_id"=>"266","sortname"=>"BY","name"=>"Belarus","phonecode"=>"375"),
            array("country_id"=>"267","sortname"=>"BE","name"=>"Belgium","phonecode"=>"32"),
            array("country_id"=>"268","sortname"=>"BZ","name"=>"Belize","phonecode"=>"501"),
            array("country_id"=>"269","sortname"=>"BJ","name"=>"Benin","phonecode"=>"229"),
            array("country_id"=>"270","sortname"=>"BM","name"=>"Bermuda","phonecode"=>"1441"),
            array("country_id"=>"271","sortname"=>"BT","name"=>"Bhutan","phonecode"=>"975"),
            array("country_id"=>"272","sortname"=>"BO","name"=>"Bolivia","phonecode"=>"591"),
            array("country_id"=>"273","sortname"=>"BA","name"=>"Bosnia and Herzegovina","phonecode"=>"387"),
            array("country_id"=>"274","sortname"=>"BW","name"=>"Botswana","phonecode"=>"267"),
            array("country_id"=>"275","sortname"=>"BV","name"=>"Bouvet Island","phonecode"=>"0"),
            array("country_id"=>"276","sortname"=>"BR","name"=>"Brazil","phonecode"=>"55"),
            array("country_id"=>"277","sortname"=>"IO","name"=>"British Indian Ocean Territory","phonecode"=>"246"),
            array("country_id"=>"278","sortname"=>"BN","name"=>"Brunei","phonecode"=>"673"),
            array("country_id"=>"279","sortname"=>"BG","name"=>"Bulgaria","phonecode"=>"359"),
            array("country_id"=>"280","sortname"=>"BF","name"=>"Burkina Faso","phonecode"=>"226"),
            array("country_id"=>"281","sortname"=>"BI","name"=>"Burundi","phonecode"=>"257"),
            array("country_id"=>"282","sortname"=>"KH","name"=>"Cambodia","phonecode"=>"855"),
            array("country_id"=>"283","sortname"=>"CM","name"=>"Cameroon","phonecode"=>"237"),
            array("country_id"=>"284","sortname"=>"CA","name"=>"Canada","phonecode"=>"1"),
            array("country_id"=>"285","sortname"=>"CV","name"=>"Cape Verde","phonecode"=>"238"),
            array("country_id"=>"286","sortname"=>"KY","name"=>"Cayman Islands","phonecode"=>"1345"),
            array("country_id"=>"287","sortname"=>"CF","name"=>"Central African Republic","phonecode"=>"236"),
            array("country_id"=>"288","sortname"=>"TD","name"=>"Chad","phonecode"=>"235"),
            array("country_id"=>"289","sortname"=>"CL","name"=>"Chile","phonecode"=>"56"),
            array("country_id"=>"290","sortname"=>"CN","name"=>"China","phonecode"=>"86"),
            array("country_id"=>"291","sortname"=>"CX","name"=>"Christmas Island","phonecode"=>"61"),
            array("country_id"=>"292","sortname"=>"CC","name"=>"Cocos (Keeling) Islands","phonecode"=>"672"),
            array("country_id"=>"293","sortname"=>"CO","name"=>"Colombia","phonecode"=>"57"),
            array("country_id"=>"294","sortname"=>"KM","name"=>"Comoros","phonecode"=>"269"),
            array("country_id"=>"295","sortname"=>"CG","name"=>"Republic Of The Congo","phonecode"=>"242"),
            array("country_id"=>"296","sortname"=>"CD","name"=>"Democratic Republic Of The Congo","phonecode"=>"242"),
            array("country_id"=>"297","sortname"=>"CK","name"=>"Cook Islands","phonecode"=>"682"),
            array("country_id"=>"298","sortname"=>"CR","name"=>"Costa Rica","phonecode"=>"506"),
            array("country_id"=>"299","sortname"=>"CI","name"=>"Cote D'Ivoire (Ivory Coast)","phonecode"=>"225"),
            array("country_id"=>"300","sortname"=>"HR","name"=>"Croatia (Hrvatska)","phonecode"=>"385"),
            array("country_id"=>"301","sortname"=>"CU","name"=>"Cuba","phonecode"=>"53"),
            array("country_id"=>"302","sortname"=>"CY","name"=>"Cyprus","phonecode"=>"357"),
            array("country_id"=>"303","sortname"=>"CZ","name"=>"Czech Republic","phonecode"=>"420"),
            array("country_id"=>"304","sortname"=>"DK","name"=>"Denmark","phonecode"=>"45"),
            array("country_id"=>"305","sortname"=>"DJ","name"=>"Djibouti","phonecode"=>"253"),
            array("country_id"=>"306","sortname"=>"DM","name"=>"Dominica","phonecode"=>"1767"),
            array("country_id"=>"307","sortname"=>"DO","name"=>"Dominican Republic","phonecode"=>"1809"),
            array("country_id"=>"308","sortname"=>"TP","name"=>"East Timor","phonecode"=>"670"),
            array("country_id"=>"309","sortname"=>"EC","name"=>"Ecuador","phonecode"=>"593"),
            array("country_id"=>"310","sortname"=>"EG","name"=>"Egypt","phonecode"=>"20"),
            array("country_id"=>"311","sortname"=>"SV","name"=>"El Salvador","phonecode"=>"503"),
            array("country_id"=>"312","sortname"=>"GQ","name"=>"Equatorial Guinea","phonecode"=>"240"),
            array("country_id"=>"313","sortname"=>"ER","name"=>"Eritrea","phonecode"=>"291"),
            array("country_id"=>"314","sortname"=>"EE","name"=>"Estonia","phonecode"=>"372"),
            array("country_id"=>"315","sortname"=>"ET","name"=>"Ethiopia","phonecode"=>"251"),
            array("country_id"=>"316","sortname"=>"XA","name"=>"External Territories of Australia","phonecode"=>"61"),
            array("country_id"=>"317","sortname"=>"FK","name"=>"Falkland Islands","phonecode"=>"500"),
            array("country_id"=>"318","sortname"=>"FO","name"=>"Faroe Islands","phonecode"=>"298"),
            array("country_id"=>"319","sortname"=>"FJ","name"=>"Fiji Islands","phonecode"=>"679"),
            array("country_id"=>"320","sortname"=>"FI","name"=>"Finland","phonecode"=>"358"),
            array("country_id"=>"321","sortname"=>"FR","name"=>"France","phonecode"=>"33"),
            array("country_id"=>"322","sortname"=>"GF","name"=>"French Guiana","phonecode"=>"594"),
            array("country_id"=>"323","sortname"=>"PF","name"=>"French Polynesia","phonecode"=>"689"),
            array("country_id"=>"324","sortname"=>"TF","name"=>"French Southern Territories","phonecode"=>"0"),
            array("country_id"=>"325","sortname"=>"GA","name"=>"Gabon","phonecode"=>"241"),
            array("country_id"=>"326","sortname"=>"GM","name"=>"Gambia The","phonecode"=>"220"),
            array("country_id"=>"327","sortname"=>"GE","name"=>"Georgia","phonecode"=>"995"),
            array("country_id"=>"328","sortname"=>"DE","name"=>"Germany","phonecode"=>"49"),
            array("country_id"=>"329","sortname"=>"GH","name"=>"Ghana","phonecode"=>"233"),
            array("country_id"=>"330","sortname"=>"GI","name"=>"Gibraltar","phonecode"=>"350"),
            array("country_id"=>"331","sortname"=>"GR","name"=>"Greece","phonecode"=>"30"),
            array("country_id"=>"332","sortname"=>"GL","name"=>"Greenland","phonecode"=>"299"),
            array("country_id"=>"333","sortname"=>"GD","name"=>"Grenada","phonecode"=>"1473"),
            array("country_id"=>"334","sortname"=>"GP","name"=>"Guadeloupe","phonecode"=>"590"),
            array("country_id"=>"335","sortname"=>"GU","name"=>"Guam","phonecode"=>"1671"),
            array("country_id"=>"336","sortname"=>"GT","name"=>"Guatemala","phonecode"=>"502"),
            array("country_id"=>"337","sortname"=>"XU","name"=>"Guernsey and Alderney","phonecode"=>"44"),
            array("country_id"=>"338","sortname"=>"GN","name"=>"Guinea","phonecode"=>"224"),
            array("country_id"=>"339","sortname"=>"GW","name"=>"Guinea-Bissau","phonecode"=>"245"),
            array("country_id"=>"340","sortname"=>"GY","name"=>"Guyana","phonecode"=>"592"),
            array("country_id"=>"341","sortname"=>"HT","name"=>"Haiti","phonecode"=>"509"),
            array("country_id"=>"342","sortname"=>"HM","name"=>"Heard and McDonald Islands","phonecode"=>"0"),
            array("country_id"=>"343","sortname"=>"HN","name"=>"Honduras","phonecode"=>"504"),
            array("country_id"=>"344","sortname"=>"HK","name"=>"Hong Kong S.A.R.","phonecode"=>"852"),
            array("country_id"=>"345","sortname"=>"HU","name"=>"Hungary","phonecode"=>"36"),
            array("country_id"=>"346","sortname"=>"IS","name"=>"Iceland","phonecode"=>"354"),
            array("country_id"=>"347","sortname"=>"IN","name"=>"India","phonecode"=>"91"),
            array("country_id"=>"348","sortname"=>"ID","name"=>"Indonesia","phonecode"=>"62"),
            array("country_id"=>"349","sortname"=>"IR","name"=>"Iran","phonecode"=>"98"),
            array("country_id"=>"350","sortname"=>"IQ","name"=>"Iraq","phonecode"=>"964"),
            array("country_id"=>"351","sortname"=>"IE","name"=>"Ireland","phonecode"=>"353"),
            array("country_id"=>"352","sortname"=>"IL","name"=>"Israel","phonecode"=>"972"),
            array("country_id"=>"353","sortname"=>"IT","name"=>"Italy","phonecode"=>"39"),
            array("country_id"=>"354","sortname"=>"JM","name"=>"Jamaica","phonecode"=>"1876"),
            array("country_id"=>"355","sortname"=>"JP","name"=>"Japan","phonecode"=>"81"),
            array("country_id"=>"356","sortname"=>"XJ","name"=>"Jersey","phonecode"=>"44"),
            array("country_id"=>"357","sortname"=>"JO","name"=>"Jordan","phonecode"=>"962"),
            array("country_id"=>"358","sortname"=>"KZ","name"=>"Kazakhstan","phonecode"=>"7"),
            array("country_id"=>"359","sortname"=>"KE","name"=>"Kenya","phonecode"=>"254"),
            array("country_id"=>"360","sortname"=>"KI","name"=>"Kiribati","phonecode"=>"686"),
            array("country_id"=>"361","sortname"=>"KP","name"=>"Korea North","phonecode"=>"850"),
            array("country_id"=>"362","sortname"=>"KR","name"=>"Korea South","phonecode"=>"82"),
            array("country_id"=>"363","sortname"=>"KW","name"=>"Kuwait","phonecode"=>"965"),
            array("country_id"=>"364","sortname"=>"KG","name"=>"Kyrgyzstan","phonecode"=>"996"),
            array("country_id"=>"365","sortname"=>"LA","name"=>"Laos","phonecode"=>"856"),
            array("country_id"=>"366","sortname"=>"LV","name"=>"Latvia","phonecode"=>"371"),
            array("country_id"=>"367","sortname"=>"LB","name"=>"Lebanon","phonecode"=>"961"),
            array("country_id"=>"368","sortname"=>"LS","name"=>"Lesotho","phonecode"=>"266"),
            array("country_id"=>"369","sortname"=>"LR","name"=>"Liberia","phonecode"=>"231"),
            array("country_id"=>"370","sortname"=>"LY","name"=>"Libya","phonecode"=>"218"),
            array("country_id"=>"371","sortname"=>"LI","name"=>"Liechtenstein","phonecode"=>"423"),
            array("country_id"=>"372","sortname"=>"LT","name"=>"Lithuania","phonecode"=>"370"),
            array("country_id"=>"373","sortname"=>"LU","name"=>"Luxembourg","phonecode"=>"352"),
            array("country_id"=>"374","sortname"=>"MO","name"=>"Macau S.A.R.","phonecode"=>"853"),
            array("country_id"=>"375","sortname"=>"MK","name"=>"Macedonia","phonecode"=>"389"),
            array("country_id"=>"376","sortname"=>"MG","name"=>"Madagascar","phonecode"=>"261"),
            array("country_id"=>"377","sortname"=>"MW","name"=>"Malawi","phonecode"=>"265"),
            array("country_id"=>"378","sortname"=>"MY","name"=>"Malaysia","phonecode"=>"60"),
            array("country_id"=>"379","sortname"=>"MV","name"=>"Maldives","phonecode"=>"960"),
            array("country_id"=>"380","sortname"=>"ML","name"=>"Mali","phonecode"=>"223"),
            array("country_id"=>"381","sortname"=>"MT","name"=>"Malta","phonecode"=>"356"),
            array("country_id"=>"382","sortname"=>"XM","name"=>"Man (Isle of)","phonecode"=>"44"),
            array("country_id"=>"383","sortname"=>"MH","name"=>"Marshall Islands","phonecode"=>"692"),
            array("country_id"=>"384","sortname"=>"MQ","name"=>"Martinique","phonecode"=>"596"),
            array("country_id"=>"385","sortname"=>"MR","name"=>"Mauritania","phonecode"=>"222"),
            array("country_id"=>"386","sortname"=>"MU","name"=>"Mauritius","phonecode"=>"230"),
            array("country_id"=>"387","sortname"=>"YT","name"=>"Mayotte","phonecode"=>"269"),
            array("country_id"=>"388","sortname"=>"MX","name"=>"Mexico","phonecode"=>"52"),
            array("country_id"=>"389","sortname"=>"FM","name"=>"Micronesia","phonecode"=>"691"),
            array("country_id"=>"390","sortname"=>"MD","name"=>"Moldova","phonecode"=>"373"),
            array("country_id"=>"391","sortname"=>"MC","name"=>"Monaco","phonecode"=>"377"),
            array("country_id"=>"392","sortname"=>"MN","name"=>"Mongolia","phonecode"=>"976"),
            array("country_id"=>"393","sortname"=>"MS","name"=>"Montserrat","phonecode"=>"1664"),
            array("country_id"=>"394","sortname"=>"MA","name"=>"Morocco","phonecode"=>"212"),
            array("country_id"=>"395","sortname"=>"MZ","name"=>"Mozambique","phonecode"=>"258"),
            array("country_id"=>"396","sortname"=>"MM","name"=>"Myanmar","phonecode"=>"95"),
            array("country_id"=>"397","sortname"=>"NA","name"=>"Namibia","phonecode"=>"264"),
            array("country_id"=>"398","sortname"=>"NR","name"=>"Nauru","phonecode"=>"674"),
            array("country_id"=>"399","sortname"=>"NP","name"=>"Nepal","phonecode"=>"977"),
            array("country_id"=>"400","sortname"=>"AN","name"=>"Netherlands Antilles","phonecode"=>"599"),
            array("country_id"=>"401","sortname"=>"NL","name"=>"Netherlands The","phonecode"=>"31"),
            array("country_id"=>"402","sortname"=>"NC","name"=>"New Caledonia","phonecode"=>"687"),
            array("country_id"=>"403","sortname"=>"NZ","name"=>"New Zealand","phonecode"=>"64"),
            array("country_id"=>"404","sortname"=>"NI","name"=>"Nicaragua","phonecode"=>"505"),
            array("country_id"=>"405","sortname"=>"NE","name"=>"Niger","phonecode"=>"227"),
            array("country_id"=>"406","sortname"=>"NG","name"=>"Nigeria","phonecode"=>"234"),
            array("country_id"=>"407","sortname"=>"NU","name"=>"Niue","phonecode"=>"683"),
            array("country_id"=>"408","sortname"=>"NF","name"=>"Norfolk Island","phonecode"=>"672"),
            array("country_id"=>"409","sortname"=>"MP","name"=>"Northern Mariana Islands","phonecode"=>"1670"),
            array("country_id"=>"410","sortname"=>"NO","name"=>"Norway","phonecode"=>"47"),
            array("country_id"=>"411","sortname"=>"OM","name"=>"Oman","phonecode"=>"968"),
            array("country_id"=>"412","sortname"=>"PK","name"=>"Pakistan","phonecode"=>"92"),
            array("country_id"=>"413","sortname"=>"PW","name"=>"Palau","phonecode"=>"680"),
            array("country_id"=>"414","sortname"=>"PS","name"=>"Palestinian Territory Occupied","phonecode"=>"970"),
            array("country_id"=>"415","sortname"=>"PA","name"=>"Panama","phonecode"=>"507"),
            array("country_id"=>"416","sortname"=>"PG","name"=>"Papua new Guinea","phonecode"=>"675"),
            array("country_id"=>"417","sortname"=>"PY","name"=>"Paraguay","phonecode"=>"595"),
            array("country_id"=>"418","sortname"=>"PE","name"=>"Peru","phonecode"=>"51"),
            array("country_id"=>"419","sortname"=>"PH","name"=>"Philippines","phonecode"=>"63"),
            array("country_id"=>"420","sortname"=>"PN","name"=>"Pitcairn Island","phonecode"=>"0"),
            array("country_id"=>"421","sortname"=>"PL","name"=>"Poland","phonecode"=>"48"),
            array("country_id"=>"422","sortname"=>"PT","name"=>"Portugal","phonecode"=>"351"),
            array("country_id"=>"423","sortname"=>"PR","name"=>"Puerto Rico","phonecode"=>"1787"),
            array("country_id"=>"424","sortname"=>"QA","name"=>"Qatar","phonecode"=>"974"),
            array("country_id"=>"425","sortname"=>"RE","name"=>"Reunion","phonecode"=>"262"),
            array("country_id"=>"426","sortname"=>"RO","name"=>"Romania","phonecode"=>"40"),
            array("country_id"=>"427","sortname"=>"RU","name"=>"Russia","phonecode"=>"70"),
            array("country_id"=>"428","sortname"=>"RW","name"=>"Rwanda","phonecode"=>"250"),
            array("country_id"=>"429","sortname"=>"SH","name"=>"Saint Helena","phonecode"=>"290"),
            array("country_id"=>"430","sortname"=>"KN","name"=>"Saint Kitts And Nevis","phonecode"=>"1869"),
            array("country_id"=>"431","sortname"=>"LC","name"=>"Saint Lucia","phonecode"=>"1758"),
            array("country_id"=>"432","sortname"=>"PM","name"=>"Saint Pierre and Miquelon","phonecode"=>"508"),
            array("country_id"=>"433","sortname"=>"VC","name"=>"Saint Vincent And The Grenadines","phonecode"=>"1784"),
            array("country_id"=>"434","sortname"=>"WS","name"=>"Samoa","phonecode"=>"684"),
            array("country_id"=>"435","sortname"=>"SM","name"=>"San Marino","phonecode"=>"378"),
            array("country_id"=>"436","sortname"=>"ST","name"=>"Sao Tome and Principe","phonecode"=>"239"),
            array("country_id"=>"437","sortname"=>"SA","name"=>"Saudi Arabia","phonecode"=>"966"),
            array("country_id"=>"438","sortname"=>"SN","name"=>"Senegal","phonecode"=>"221"),
            array("country_id"=>"439","sortname"=>"RS","name"=>"Serbia","phonecode"=>"381"),
            array("country_id"=>"440","sortname"=>"SC","name"=>"Seychelles","phonecode"=>"248"),
            array("country_id"=>"441","sortname"=>"SL","name"=>"Sierra Leone","phonecode"=>"232"),
            array("country_id"=>"442","sortname"=>"SG","name"=>"Singapore","phonecode"=>"65"),
            array("country_id"=>"443","sortname"=>"SK","name"=>"Slovakia","phonecode"=>"421"),
            array("country_id"=>"444","sortname"=>"SI","name"=>"Slovenia","phonecode"=>"386"),
            array("country_id"=>"445","sortname"=>"XG","name"=>"Smaller Territories of the UK","phonecode"=>"44"),
            array("country_id"=>"446","sortname"=>"SB","name"=>"Solomon Islands","phonecode"=>"677"),
            array("country_id"=>"447","sortname"=>"SO","name"=>"Somalia","phonecode"=>"252"),
            array("country_id"=>"448","sortname"=>"ZA","name"=>"South Africa","phonecode"=>"27"),
            array("country_id"=>"449","sortname"=>"GS","name"=>"South Georgia","phonecode"=>"0"),
            array("country_id"=>"450","sortname"=>"SS","name"=>"South Sudan","phonecode"=>"211"),
            array("country_id"=>"451","sortname"=>"ES","name"=>"Spain","phonecode"=>"34"),
            array("country_id"=>"452","sortname"=>"LK","name"=>"Sri Lanka","phonecode"=>"94"),
            array("country_id"=>"453","sortname"=>"SD","name"=>"Sudan","phonecode"=>"249"),
            array("country_id"=>"454","sortname"=>"SR","name"=>"Suriname","phonecode"=>"597"),
            array("country_id"=>"455","sortname"=>"SJ","name"=>"Svalbard And Jan Mayen Islands","phonecode"=>"47"),
            array("country_id"=>"456","sortname"=>"SZ","name"=>"Swaziland","phonecode"=>"268"),
            array("country_id"=>"457","sortname"=>"SE","name"=>"Sweden","phonecode"=>"46"),
            array("country_id"=>"458","sortname"=>"CH","name"=>"Switzerland","phonecode"=>"41"),
            array("country_id"=>"459","sortname"=>"SY","name"=>"Syria","phonecode"=>"963"),
            array("country_id"=>"460","sortname"=>"TW","name"=>"Taiwan","phonecode"=>"886"),
            array("country_id"=>"461","sortname"=>"TJ","name"=>"Tajikistan","phonecode"=>"992"),
            array("country_id"=>"462","sortname"=>"TZ","name"=>"Tanzania","phonecode"=>"255"),
            array("country_id"=>"463","sortname"=>"TH","name"=>"Thailand","phonecode"=>"66"),
            array("country_id"=>"464","sortname"=>"TG","name"=>"Togo","phonecode"=>"228"),
            array("country_id"=>"465","sortname"=>"TK","name"=>"Tokelau","phonecode"=>"690"),
            array("country_id"=>"466","sortname"=>"TO","name"=>"Tonga","phonecode"=>"676"),
            array("country_id"=>"467","sortname"=>"TT","name"=>"Trinidad And Tobago","phonecode"=>"1868"),
            array("country_id"=>"468","sortname"=>"TN","name"=>"Tunisia","phonecode"=>"216"),
            array("country_id"=>"469","sortname"=>"TR","name"=>"Turkey","phonecode"=>"90"),
            array("country_id"=>"470","sortname"=>"TM","name"=>"Turkmenistan","phonecode"=>"7370"),
            array("country_id"=>"471","sortname"=>"TC","name"=>"Turks And Caicos Islands","phonecode"=>"1649"),
            array("country_id"=>"472","sortname"=>"TV","name"=>"Tuvalu","phonecode"=>"688"),
            array("country_id"=>"473","sortname"=>"UG","name"=>"Uganda","phonecode"=>"256"),
            array("country_id"=>"474","sortname"=>"UA","name"=>"Ukraine","phonecode"=>"380"),
            array("country_id"=>"475","sortname"=>"AE","name"=>"United Arab Emirates","phonecode"=>"971"),
            array("country_id"=>"476","sortname"=>"GB","name"=>"United Kingdom","phonecode"=>"44"),
            array("country_id"=>"477","sortname"=>"US","name"=>"United States","phonecode"=>"1"),
            array("country_id"=>"478","sortname"=>"UM","name"=>"United States Minor Outlying Islands","phonecode"=>"1"),
            array("country_id"=>"479","sortname"=>"UY","name"=>"Uruguay","phonecode"=>"598"),
            array("country_id"=>"480","sortname"=>"UZ","name"=>"Uzbekistan","phonecode"=>"998"),
            array("country_id"=>"481","sortname"=>"VU","name"=>"Vanuatu","phonecode"=>"678"),
            array("country_id"=>"482","sortname"=>"VA","name"=>"Vatican City State (Holy See)","phonecode"=>"39"),
            array("country_id"=>"483","sortname"=>"VE","name"=>"Venezuela","phonecode"=>"58"),
            array("country_id"=>"484","sortname"=>"VN","name"=>"Vietnam","phonecode"=>"84"),
            array("country_id"=>"485","sortname"=>"VG","name"=>"Virgin Islands (British)","phonecode"=>"1284"),
            array("country_id"=>"486","sortname"=>"VI","name"=>"Virgin Islands (US)","phonecode"=>"1340"),
            array("country_id"=>"487","sortname"=>"WF","name"=>"Wallis And Futuna Islands","phonecode"=>"681"),
            array("country_id"=>"488","sortname"=>"EH","name"=>"Western Sahara","phonecode"=>"212"),
            array("country_id"=>"489","sortname"=>"YE","name"=>"Yemen","phonecode"=>"967"),
            array("country_id"=>"490","sortname"=>"YU","name"=>"Yugoslavia","phonecode"=>"38"),
            array("country_id"=>"491","sortname"=>"ZM","name"=>"Zambia","phonecode"=>"260"),
            array("country_id"=>"492","sortname"=>"ZW","name"=>"Zimbabwe","phonecode"=>"263"),
        ];

        DB::table('country')->insert($country);
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('country');
    }
};
